# Credit cards
simple credit card regression


In [1]:
# Get data from here:
# https://packt.link/wensZ

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 400. # High res

In [3]:
df = pd.read_csv('Data/cleaned_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26664 entries, 0 to 26663
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   Unnamed: 0                  26664 non-null  int64 
 1   ID                          26664 non-null  object
 2   LIMIT_BAL                   26664 non-null  int64 
 3   SEX                         26664 non-null  int64 
 4   EDUCATION                   26664 non-null  int64 
 5   MARRIAGE                    26664 non-null  int64 
 6   AGE                         26664 non-null  int64 
 7   PAY_1                       26664 non-null  int64 
 8   PAY_2                       26664 non-null  int64 
 9   PAY_3                       26664 non-null  int64 
 10  PAY_4                       26664 non-null  int64 
 11  PAY_5                       26664 non-null  int64 
 12  PAY_6                       26664 non-null  int64 
 13  BILL_AMT1                   26664 non-null  in

In [4]:
df['default payment next month'].mean()

0.2217971797179718

In [5]:
df.groupby('default payment next month')['ID'].count()

default payment next month
0    20750
1     5914
Name: ID, dtype: int64

In [6]:
from sklearn.linear_model import LogisticRegression
my_lr = LogisticRegression()

In [8]:
my_lr = LogisticRegression(penalty='l2', dual=False,
                          tol=0.0001, C=1.0,
                          fit_intercept=True,
                          intercept_scaling=1,
                          class_weight=None,
                          random_state=None,
                          solver='lbfgs',
                          max_iter=100,
                          multi_class='auto',
                          verbose=1,
                          warm_start=False,
                          n_jobs=None,
                          l1_ratio=None)

In [9]:
my_lr.C = 0.1
my_lr.solver = 'liblinear'
my_lr

LogisticRegression(C=0.1, solver='liblinear', verbose=1)

In [10]:
X = df['EDUCATION'][0:10].values.reshape(-1,1)
X

array([[2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [3],
       [3]])

In [11]:
y = df['default payment next month'][0:10].values
y

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
my_lr.fit(X, y)

[LibLinear]

LogisticRegression(C=0.1, solver='liblinear', verbose=1)

In [13]:
new_X = df['EDUCATION'][10:20].values.reshape(-1, 1)
my_lr.predict(new_X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
df['default payment next month'][10:20].values


array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0])