In [12]:
import numpy as np
from numpy.random import default_rng
rg = default_rng(12345)

In [13]:
random_integers = rg.integers(low=1, high=5, size=100)
random_integers[:5]

array([3, 1, 4, 2, 1])

In [14]:
# Create a mask
is_equal_to_3 = random_integers == 3

In [15]:
is_equal_to_3[:5]

array([ True, False, False, False, False])

In [16]:
is_1 = random_integers == 1
is_2 = random_integers == 2
is_3 = random_integers == 3
is_4 = random_integers ==4

In [10]:
print(f"1:{sum(is_1)}, 2:{sum(is_2)}, 3:{sum(is_3)}, 4:{sum(is_4)}")

1:23, 2:27, 3:31, 4:19


In [11]:
# use boolean array to mask values
random_integers[is_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3])